# Ⅰ 데이터 처리

In [1]:
A=[[176.5,1.2],[169.2,0.8],[180.3,0.1],[162.7,0.5]]
print(A[0])


[176.5, 1.2]


In [2]:
a=[1,2,3]
b=[2,3,4]
print(a+b)


[1, 2, 3, 2, 3, 4]


In [4]:
import numpy as np
AA = np.array(a)
BB = np.array(b)

print(AA)
print(BB)

print(AA/BB)
print(AA*1.3)



[1 2 3]
[2 3 4]
[0.5        0.66666667 0.75      ]
[1.3 2.6 3.9]


In [7]:
A=[[176.5,1.2],[169.2,0.8],[180.3,0.1],[162.7,0.5]]
PA = np.array(A)

print(PA)

# print(PA[:,0:])
print(PA[:,1]) # 모든 행의 첫 번째 열 출력

print(PA.shape) # 배열의 형태를 튜플로 반환

[[1.765e+02 1.200e+00]
 [1.692e+02 8.000e-01]
 [1.803e+02 1.000e-01]
 [1.627e+02 5.000e-01]]
[[1.765e+02 1.200e+00]
 [1.692e+02 8.000e-01]
 [1.803e+02 1.000e-01]
 [1.627e+02 5.000e-01]]
[1.2 0.8 0.1 0.5]
(4, 2)


**표준화**

In [20]:
import numpy as np

Health=np.array([[176.5,1.2],[169.2,0.8],[180.3,0.1],[162.7,0.5]])
Health_std=np.copy(Health) #배열의 복사본

# print(Health.shape[1]) # 열의 갯수를 반환


for i in range(Health.shape[1]):
    # print('가져온 데이터', Health[:, i])
    avg=np.mean(Health[:, i])  # 모든 행의 i번째 열
    # print('평균', avg)
    std=np.std(Health[:, i])      # 모든 행의 i번째 열
    # print('표준편차', std)
    Health_std[:,i]=(Health[:, i] - avg) / std
print(Health_std)


2
가져온 데이터 [176.5 169.2 180.3 162.7]
평균 172.175
표준편차 6.77029356822879
가져온 데이터 [1.2 0.8 0.1 0.5]
평균 0.65
표준편차 0.40311288741492746
[[ 0.63882016  1.36438208]
 [-0.43941965  0.3721042 ]
 [ 1.20009567 -1.36438208]
 [-1.39949618 -0.3721042 ]]


**정규화**

In [21]:
import numpy as np

Health = np.array([[176.5, 1.2], [169.2, 0.8], [180.3, 0.1], [162.7, 0.5]])
Health_norm = np.copy(Health)
for i in range(Health.shape[1]): # 각 열에 대해서 반복
    min_val = np.min(Health[:, i]) # 각 열의 최소값
    max_val = np.max(Health[:, i]) # 각 열의 최대값
    print(min_val, max_val)
    Health_norm[:, i] = (Health[:, i] - min_val) / (max_val - min_val) # 정규화 수행
print(Health_norm)


162.7 180.3
0.1 1.2
[[0.78409091 1.        ]
 [0.36931818 0.63636364]
 [1.         0.        ]
 [0.         0.36363636]]


**sklearn Library**

In [22]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# 표준화 - 사이킷런 라이브러리 활용
Health = np.array([[176.5, 1.2], [169.2, 0.8], [180.3, 0.1], [162.7, 0.5]])
scaler = StandardScaler()  # StandardScaler 인스턴스 생성
Health_std2 = scaler.fit_transform(Health)  # fit_transform 메소드로 데이터 표준화
print('표준화(사이킷런 라이브러리) : \n', Health_std2)
print()


표준화(사이킷런 라이브러리) : 
 [[ 0.63882016  1.36438208]
 [-0.43941965  0.3721042 ]
 [ 1.20009567 -1.36438208]
 [-1.39949618 -0.3721042 ]]



In [23]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# 정규화 - 사이킷런 라이브러리 활용
Health = np.array([[176.5, 1.2], [169.2, 0.8], [180.3, 0.1], [162.7, 0.5]])
scaler = MinMaxScaler()  # MinMaxScaler 인스턴스 생성
Health_norm2 = scaler.fit_transform(Health)  # fit_transform 메소드로 데이터 정규화
print(Health_norm2)


[[0.78409091 1.        ]
 [0.36931818 0.63636364]
 [1.         0.        ]
 [0.         0.36363636]]
